# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='save',
        ),
    ]
